name: Basic CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Success Message
        run: echo "CI/CD Pipeline executed successfully!"
